#parameters:

services:
    blog.exception_listener:
        class: Blogger\BlogBundle\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    apikey_authenticator:
        class:  Blogger\BlogBundle\Security\ApiKeyAuthenticator
        arguments: [@doctrine.orm.entity_manager]
        public: false

    admin.category:
        class: Blogger\BlogBundle\Admin\UserAdmin
        arguments: [~, Blogger\BlogBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User }

    comments.category:
        class: Blogger\BlogBundle\Admin\CommentAdmin
        arguments: [~, Blogger\BlogBundle\Entity\Comment, ~, @doctrine.orm.entity_manager]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Comment }
