#parameters:

services:
    blog.exception_listener:
        class: Blogger\BlogBundle\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    apikey_authenticator:
        class:  Blogger\BlogBundle\Security\ApiKeyAuthenticator
        arguments: [@doctrine.orm.entity_manager]
        public: false

