<?php

namespace Blogger\BlogBundle\Entity\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function getImages()
    {
        return $qb = $this->createQueryBuilder('i')
            ->select('i.name')
            ->getQuery()
            ->getResult();
    }
}